# site title
title: Ick's Blog

# user name or organization name
user: lisaac

# issue repository
repository: blog

# multi-author
authors: 'lisaac.cn@gmail.com'

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 761408cdb76b62087c46935b03fb13b6e4d02491

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
